# -*- coding: utf-8 -*-
"""LAB3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IR_6BgvhbDjX7GZVzvJPA6kz-JhKmiy3
"""

import random
import time
import matplotlib.pyplot as plt

#List to store data for plotting
times=[]
temps=[]
humidity=[]

# File names
cvs_file="data_log.cvs "
txt_file="data _log.txt"

#write header with error handling
try:
   with open (cvs_file,"w") as f:
       f.write ("Time Temperature Humidity\n")

except IOError as e:
    print("Error creating files :",e)

#Data logging loop
for t in range (10):
    try:
      temp=25+random. uniform(-1,1)
      hum=60+random.uniform(-5,5)

      temps.append(temp)
      humidity.append(hum)
      times.append(t)

      with open (cvs_file,"a") as f:
        f.write(f"{t},{temp:.2f},{hum:.2f}\n")
      with open(txt_file,"a")as f:
        f.write(f"{t},{temp:.2f},{hum:.2f}\n")

      time .sleep(0.5)

    except IOError as e:
      print("File write error:",e)

plt.plot(times,temps,label="Temperature(c)")
plt.plot(times,temps,label="Humidity(%)")
plt.xlabel("Time(s)")
plt.ylabel("Values")
plt.title("Temperature and Humidity Log")
plt.legend()
plt.show()