# -*- coding: utf-8 -*-
"""LAB 1 PYTHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGX-7-u0Gh8nKTrhnSbV3Ge8aOneS-91
"""

while True:
  try :
    voltage = float(input("Enter voltage(V):"))
    resistance=float(input("Enter resistance(ohms):"))

    if resistance !=0:
      current =voltage/resistance
      power=voltage *current
      print(f"Current(A):{current}")
      print(f"Power(W):{power}")
    else:
      print("Error:Resistance cannot be zero.")
  except ValueError:
    print("Error: Please enter numbers only.")
  #Now 'break' work because it is inside the 'while' loop
  cont= input("Do you want to calculate again ?(y/n):")
  if cont.lower()!='y':
    break