# -*- coding: utf-8 -*-
"""lab-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ndirangubanett-stack/c61aa5e01b2304f57093f43c38c986d4/lab-2.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
R= 1000 # Ohms
C=1e-6 #Farads
V=5 # Volts
tau=R* C

t=np.linspace(0,0.01,1000)
Vc_charging =V*(1-np.exp(-t/tau))

plt.figure(figsize=(8,4))
plt.plot(t,Vc_charging,label=f"Charging(tau={tau:3f}s)")
plt.xlabel("Time(s)")
plt.ylabel("Voltage(V)")
plt.title("Lab 2:RC Charging Curve")
plt.legend()
plt.grid(True)
plt.show()

#Task: modifying for discharging
Vc_discharging=V * np.exp(-t/tau)

plt.figure(figsize=(8,4))
plt.plot(t,Vc_discharging, color='red',label="Discharging")
plt.xlabel("Time(s)")
plt.ylabel("Voltage(V)")
plt.title("Lab 2: RC Discharging Curve")
plt.legend()
plt.grid(True)
plt.show()